---
ID: "d1ef4670-f707-5d1b-b51f-21f8af619bbd"
Parent: "6b751715-aceb-5a9c-8322-f7259d75d53b"
Template: "6b751715-aceb-5a9c-8322-f7259d75d53b"
Path: "/sitecore/templates/Project/multisite_poc/Styleguide-RouteFields/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220721T093926Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "698aef98-833f-42a7-a8be-97e289f41f88"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220721T093926Z
